SET SEARCH_PATH TO public, "$user","public";

-- Lock Database
UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = 'LDEV-FIZZAHHASHMI (192.168.1.136)', LOCKGRANTED = NOW() WHERE ID = 1 AND LOCKED = FALSE;

SET SEARCH_PATH TO public, "$user","public";

SET SEARCH_PATH TO public, "$user","public";

-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: changelog.yaml
-- Ran at: 4/16/24, 9:52 PM
-- Against: postgres@jdbc:postgresql://localhost:5432/demo_db
-- Liquibase version: 4.27.0
-- *********************************************************************

SET SEARCH_PATH TO public, "$user","public";

-- Changeset changelog.yaml::1713286227644-1::fizzah.hashmi (generated)
SET SEARCH_PATH TO public, "$user","public";

CREATE TABLE IF NOT EXISTS public.course (completed BOOLEAN NOT NULL, id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 7) NOT NULL, author VARCHAR(255), description VARCHAR(255), title VARCHAR(255), CONSTRAINT course_pkey PRIMARY KEY (id));

INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('1713286227644-1', 'fizzah.hashmi (generated)', 'changelog.yaml', NOW(), 1, '9:bea4b4416d499c4634a21d52757b138a', 'createTable tableName=course', '', 'EXECUTED', NULL, NULL, '4.27.0', '3286378827');

-- Release Database Lock
SET SEARCH_PATH TO public, "$user","public";

UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

SET SEARCH_PATH TO public, "$user","public";

